My PR for Homework3
Otus-DevOps-2020-02/agor-dot_infra pull request #2
Opened 2020-03-18 15:03 UTC by agor-dot

# Выполнено ДЗ №3
 [x] Основное ДЗ
 [x] Задание со *

## В процессе сделано:
 - Созданы 2 виртуальные машины в GCP.
 - Настроен ssh для входа по ключам.
 - Настроен более простой вход с локальной машины на хост someinternalhost.
 - Установлен и настроен VPN сервис Pritunl.
 - Подписан сертификат и настроена работа dashboard Pritunl через него.

## Как запустить проект:
Не предполагается в данном ДЗ.

## Как проверить работоспособность:
 - Доступность VPN по FQDN: https://vpn.35.205.78.68.xip.io/login

## PR checklist
[x] Выставил label с номером домашнего задания
[x] Выставил label с темой домашнего задания

2020-03-18 19:51 UTC, mrgreyves requested changes
Здравствуйте!) У вас проблема с конфигурационным файлов впн.
```
Options error: In [CMD-LINE]:1: Error opening configuration file: cloud-bastion.ovpn
```
ДЗ возвращаю на доработку.

2020-03-19 08:13 UTC, agor-dot commented
Это очень странно, я только что перепроверил, но VPN у меня работает. Может у нас с версионностью что то не так?
OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan  9 2019

2020-03-25 05:20 UTC, mrgreyves approved these changes
Здравствуйте!) Круто что прикрутили SSL сертификат. Апрув!)

2020-03-25 05:20 UTC, mrgreyves commented on README.md
> +ProxyCommand ssh -W %h:%p alex-home@35.205.78.68
Лучше уже попробовать ProxyJump =)

2020-03-25 08:57 UTC, merged